### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by h4x0rigin** [sam-shariat/ai-post-generator#2]
When try to generate any type of content, it returns undenfined. Can you fix?

**Comment by sam-shariat** [comment]
Hey there,
My OpenAI API key usage reached the limit, so I made some changes and now you can just enter your own OpenAI API key and use the app. 
you can get one for free in here :  
[https://platform.openai.com/account/api-keys
](https://platform.openai.com/account/api-keys
)
link is available in the app.
